const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let theme=localStorage.getItem('jittoo-theme')||'dark',canvas=null,currentProject='Untitled project',selectedFileKind='image',autosaveTimer=null,restoreLast=true;
const templates=[['Product','Launch · Store · Offer','https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85'],['Fashion','Lookbook · Campaign','https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1000&q=85'],['Restaurant','Menu · Promo · Social','https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=85'],['Real estate','Listing · Property','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85'],['Beauty','Campaign · Service','https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85'],['Event','Poster · Invite','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=85'],['Personal brand','Profile · Content','https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=1000&q=85'],['Travel','Guide · Story','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=85'],['Technology','Product · Launch','https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=85']];
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
function show(v){$$('.view').forEach(x=>x.classList.remove('active'));const el=$('#'+v);if(el)el.classList.add('active');if(v==='studio')initCanvas();location.hash=v;scrollTo({top:0,behavior:'smooth'})}
function applyTheme(){document.body.classList.toggle('light',theme==='light');const b=$('#theme');if(b)b.textContent=theme==='light'?'☾':'☼';localStorage.setItem('jittoo-theme',theme)}
function renderTemplates(){const g=$('#templateGrid');if(!g)return;g.innerHTML=templates.map((x,i)=>`<button class="template" data-template-index="${i}"><img class="template-art" src="${x[2]}" alt="${x[0]}" loading="lazy"><b>${x[0]}</b><small>${x[1]}</small></button>`).join('')}
function resize(){if(!canvas)return;const s=$('#stage');if(!s)return;const w=Math.max(320,s.clientWidth-16),h=Math.max(320,s.clientHeight-16);canvas.setDimensions({width:w,height:h});canvas.requestRenderAll()}
function initCanvas(){if(canvas)return;if(typeof fabric==='undefined'){toast('Editor engine failed to load');return}canvas=new fabric.Canvas('canvas',{preserveObjectStacking:true,selection:true});resize();window.addEventListener('resize',resize,{passive:true});canvas.on('selection:created',showContext);canvas.on('selection:updated',showContext);canvas.on('selection:cleared',hideContext);canvas.on('object:modified',queueAutosave);canvas.on('object:added',queueAutosave);canvas.on('object:removed',queueAutosave);if(restoreLast)loadLastProject();restoreLast=false}
function showContext(){const c=$('#context');c?.classList.remove('hidden')}function hideContext(){const c=$('#context');c?.classList.add('hidden')}function revealCanvas(){if($('#empty'))$('#empty').classList.add('hidden')}function resetEmpty(){if($('#empty'))$('#empty').classList.remove('hidden')}
function centerObject(o){o.set({left:canvas.getWidth()/2,top:canvas.getHeight()/2,originX:'center',originY:'center'});o.setCoords()}
function clearCanvas(){if(!canvas)return;canvas.clear();canvas.backgroundColor='transparent';hideContext();resetEmpty();canvas.requestRenderAll()}
function addImage(src,name='Photo',asBackground=false){if(!canvas||!src)return;toast('Opening in Studio…');fabric.Image.fromURL(src,img=>{if(!img){toast('Could not load this image');return}if(asBackground){img.set({left:0,top:0,originX:'left',originY:'top',selectable:false,evented:false});img.scaleToWidth(canvas.getWidth());img.scaleToHeight(canvas.getHeight());canvas.add(img);canvas.sendToBack(img)}else{const maxW=canvas.getWidth()*.82,maxH=canvas.getHeight()*.82,scale=Math.min(maxW/(img.width||1),maxH/(img.height||1),1);img.set({scaleX:scale,scaleY:scale});centerObject(img);canvas.add(img);canvas.setActiveObject(img)}img.set('name',name);revealCanvas();canvas.requestRenderAll();queueAutosave();toast('Design loaded — edit it freely')},{crossOrigin:'anonymous'})}
function openStudio(src='',kind='image',name='Untitled project'){restoreLast=false;currentProject=name;$('#studioName').textContent=currentProject;show('studio');requestAnimationFrame(()=>{initCanvas();clearCanvas();requestAnimationFrame(()=>{if(src)addImage(src,kind==='background'?'Background':'Design',kind==='background')})})}
function openTemplate(i){const t=templates[i];if(!t)return;openStudio(t[2],'image',t[0]+' project')}
function openCustom(){openStudio('','image','Custom project')}
function fileToData(file,cb){const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
function pickFile(kind='image'){selectedFileKind=kind;const i=$('#localFile');if(!i)return;i.value='';i.accept=kind==='gif'?'image/gif,image/*':'image/*';i.click()}
function addText(){if(!canvas)return;const o=new fabric.IText('YOUR BUSINESS',{fontFamily:'Space Grotesk',fontSize:42,fontWeight:700,fill:'#e5d0a0',textAlign:'center'});centerObject(o);canvas.add(o);canvas.setActiveObject(o);revealCanvas();canvas.requestRenderAll();queueAutosave()}
function addShape(type='rect'){if(!canvas)return;const o=type==='circle'?new fabric.Circle({radius:70,fill:'#c9a96b'}):new fabric.Rect({width:180,height:120,rx:18,ry:18,fill:'#c9a96b'});centerObject(o);canvas.add(o);canvas.setActiveObject(o);revealCanvas();canvas.requestRenderAll();queueAutosave()}
function tool(n){const p=$('#toolPanel');if(!p)return;p.classList.remove('hidden');const buttons={add:'<button data-a="photo">Add photo</button><button data-a="background">Add background</button>',text:'<button data-a="text">Add text</button>',shape:'<button data-a="rect">Rectangle</button><button data-a="circle">Circle</button>',effect:'<button data-a="gray">Mono</button><button data-a="bright">Bright</button><button data-a="reset">Reset</button>',gif:'<button data-a="gif">Choose GIF / image</button>',layers:'<button data-a="front">Bring forward</button><button data-a="back">Send back</button><button data-a="top">Bring to front</button><button data-a="bottom">Send to back</button>'};p.innerHTML=buttons[n]||'';p.querySelectorAll('button').forEach(b=>b.onclick=()=>toolAction(b.dataset.a))}
function toolAction(a){const o=canvas?.getActiveObject();if(a==='photo')return pickFile('image');if(a==='background')return pickFile('background');if(a==='gif')return pickFile('gif');if(a==='text')return addText();if(a==='rect')return addShape();if(a==='circle')return addShape('circle');if(!o)return toast('Select an object first');if(a==='front')canvas.bringForward(o);if(a==='back')canvas.sendBackwards(o);if(a==='top')canvas.bringToFront(o);if(a==='bottom')canvas.sendToBack(o);if(a==='gray'&&o.type==='image'){o.filters=[new fabric.Image.filters.Grayscale()];o.applyFilters()}if(a==='bright'&&o.type==='image'){o.filters=[new fabric.Image.filters.Brightness({brightness:.15})];o.applyFilters()}if(a==='reset'&&o.type==='image'){o.filters=[];o.applyFilters()}canvas.requestRenderAll();queueAutosave()}
function save(){if(!canvas)return;const data=canvas.toJSON(['name']);localStorage.setItem('jittoo-project-v2',JSON.stringify({version:3,name:currentProject,updated:new Date().toISOString(),canvas:data}));localStorage.setItem('jittoo-project-name',currentProject);toast('Project saved on this device')}
function loadLastProject(){const raw=localStorage.getItem('jittoo-project-v2');if(!raw||!canvas)return;try{const p=JSON.parse(raw);currentProject=p.name||'Untitled project';$('#studioName').textContent=currentProject;canvas.loadFromJSON(p.canvas,()=>{if(canvas.getObjects().length)revealCanvas();else resetEmpty();canvas.requestRenderAll()})}catch{localStorage.removeItem('jittoo-project-v2')}}
function queueAutosave(){clearTimeout(autosaveTimer);autosaveTimer=setTimeout(save,900)}
function exportPNG(){if(!canvas)return;const a=document.createElement('a');a.download=(currentProject||'jittoo-design').replace(/[^a-z0-9_-]+/gi,'-')+'.png';a.href=canvas.toDataURL({format:'png',multiplier:2});a.click();toast('PNG exported')}
function deleteSelected(){const o=canvas?.getActiveObject();if(!o)return;canvas.remove(o);hideContext();if(!canvas.getObjects().length)resetEmpty();canvas.requestRenderAll();queueAutosave()}
function duplicateSelected(){const o=canvas?.getActiveObject();if(!o)return;o.clone(c=>{c.set({left:(o.left||0)+24,top:(o.top||0)+24});canvas.add(c);canvas.setActiveObject(c);canvas.requestRenderAll();queueAutosave()})}
function preview(){const n=$('#brandName')?.value||'Your business',t=$('#brandTagline')?.value||'Your tagline appears here.',c=$('#brandContact')?.value||'Contact information';if($('#previewName'))$('#previewName').textContent=n;if($('#previewTagline'))$('#previewTagline').textContent=t;if($('#previewContact'))$('#previewContact').textContent=c}
function loadBrand(){try{const b=JSON.parse(localStorage.getItem('jittoo-brand')||'null');if(!b)return;['name','tagline','contact','note'].forEach(k=>{const id='brand'+k[0].toUpperCase()+k.slice(1);if($('#'+id))$('#'+id).value=b[k]||''});preview()}catch{}}
function generateAI(){const q=$('#aiPrompt')?.value.trim();if(!q)return toast('Describe your creative goal first.');$('#aiResult').textContent=`CREATIVE DIRECTION\n\nGoal\n${q}\n\nComposition\nUse one clear focal subject, generous negative space and a strong visual hierarchy.\n\nStyle\nPremium editorial · restrained palette · refined typography · subtle depth.\n\nMotion\nUse a slow entrance, gentle parallax and micro-interactions only where they improve focus.`}
async function activatePremium(){const key=$('#premiumKey').value.trim(),out=$('#keyResult');if(!key)return toast('Enter your premium key');out.textContent='Checking…';try{const r=await fetch('/api/premium',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});const d=await r.json();if(d.valid){localStorage.setItem('jittoo-premium',JSON.stringify(d));$('#premiumDot').textContent='✓';out.textContent=`Premium active · ${d.enddate}`;toast('Premium activated')}else out.textContent=d.message||'Invalid key'}catch{out.textContent='Premium service unavailable'}}
function bind(){$('#theme').onclick=()=>{theme=theme==='light'?'dark':'light';applyTheme()};$('#premium').onclick=()=>$('#premiumModal').classList.remove('hidden');$('#closePremium').onclick=()=>$('#premiumModal').classList.add('hidden');$('#telegram').onclick=()=>window.open('https://t.me/vcafemm','_blank','noopener,noreferrer');$('#activate').onclick=activatePremium;$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#start').onclick=()=>openStudio();$('#customStart').onclick=openCustom;$('#openLocal').onclick=()=>pickFile('image');$('#localFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;fileToData(f,src=>openStudio(src,selectedFileKind,'Custom upload'))};$$('.visual-card').forEach(b=>b.onclick=()=>openTemplate(Number(b.dataset.templateIndex||0)));renderTemplates();$('#templateGrid').onclick=e=>{const b=e.target.closest('.template');if(b)openTemplate(+b.dataset.templateIndex)};$('#brandForm').onsubmit=e=>{e.preventDefault();localStorage.setItem('jittoo-brand',JSON.stringify({name:$('#brandName').value,tagline:$('#brandTagline').value,contact:$('#brandContact').value,note:$('#brandNote').value}));preview();toast('Business information saved')};['brandName','brandTagline','brandContact'].forEach(id=>$('#'+id).oninput=preview);$('#aiBtn').onclick=generateAI;$('#save').onclick=save;$('#export').onclick=exportPNG;$$('.tool-dock button').forEach(b=>b.onclick=()=>{$$('.tool-dock button').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool(b.dataset.tool)});$('#context').onclick=e=>{const b=e.target.closest('button'),o=canvas?.getActiveObject();if(!b||!o)return;const a=b.dataset.tool;if(a==='delete')deleteSelected();if(a==='duplicate')duplicateSelected();if(a==='front')canvas.bringForward(o);if(a==='back')canvas.sendBackwards(o);canvas.requestRenderAll();queueAutosave()};window.addEventListener('keydown',e=>{if(!canvas||!$('#studio').classList.contains('active'))return;if(e.key==='Delete'||e.key==='Backspace'){if(document.activeElement?.tagName==='INPUT'||document.activeElement?.tagName==='TEXTAREA')return;deleteSelected()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected()}})}
applyTheme();bind();preview();loadBrand();if(localStorage.getItem('jittoo-premium'))$('#premiumDot').textContent='✓';const initial=['templates','business','ai','studio'].includes(location.hash.slice(1))?location.hash.slice(1):'home';show(initial);
