const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let theme=localStorage.getItem('jittoo-theme')||'dark',canvas=null;
function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function show(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v)?.classList.add('active');location.hash=v;scrollTo(0,0);if(v==='studio')initCanvas()}
function applyTheme(){document.body.classList.toggle('light',theme==='light');$('#theme').textContent=theme==='light'?'☾':'☼';localStorage.setItem('jittoo-theme',theme)}
const data=[['Product','Launch · Store · Offer'],['Fashion','Lookbook · Campaign'],['Restaurant','Menu · Promo · Social'],['Real estate','Listing · Property'],['Beauty','Campaign · Service'],['Event','Poster · Invite'],['Personal brand','Profile · Content'],['Travel','Guide · Story'],['Technology','Product · Launch']];
function renderTemplates(){$('#templateGrid').innerHTML=data.map(x=>`<button class="template"><b>${x[0]}</b><small>${x[1]}</small></button>`).join('')}
function initCanvas(){if(canvas)return;canvas=new fabric.Canvas('canvas',{preserveObjectStacking:true});resize();addEvents();window.addEventListener('resize',resize)}
function resize(){if(!canvas)return;let s=$('#stage');canvas.setWidth(Math.max(300,s.clientWidth-20));canvas.setHeight(Math.max(300,s.clientHeight-20));canvas.requestRenderAll()}
function openStudio(src){show('studio');if(src)setImage(src)}
function setImage(src){fabric.Image.fromURL(src,img=>{let w=canvas.getWidth()*.8,h=canvas.getHeight()*.8,scale=Math.min(w/img.width,h/img.height,1);img.set({left:canvas.getWidth()/2,top:canvas.getHeight()/2,originX:'center',originY:'center',scaleX:scale,scaleY:scale});canvas.clear();canvas.add(img);canvas.setActiveObject(img);$('#empty').classList.add('hidden');canvas.requestRenderAll()},{crossOrigin:'anonymous'})}
function addText(){let o=new fabric.IText('YOUR BUSINESS',{left:canvas.getWidth()/2,top:canvas.getHeight()/2,originX:'center',originY:'center',fontFamily:'Space Grotesk',fontSize:42,fontWeight:700,fill:'#e5d0a0'});canvas.add(o);canvas.setActiveObject(o);canvas.requestRenderAll()}
function shape(circle=false){let o=circle?new fabric.Circle({radius:70,fill:'#c9a96b'}):new fabric.Rect({width:160,height:110,rx:18,ry:18,fill:'#c9a96b'});o.set({left:canvas.getWidth()/2,top:canvas.getHeight()/2,originX:'center',originY:'center'});canvas.add(o);canvas.setActiveObject(o);canvas.requestRenderAll()}
function tool(n){let p=$('#toolPanel');p.classList.remove('hidden');if(n==='add'){p.innerHTML='<button id="pick">Add photo</button><button id="clr">Clear</button>';$('#pick').onclick=()=>$('#localFile').click();$('#clr').onclick=()=>{canvas.clear();$('#empty').classList.remove('hidden')}}if(n==='text'){p.innerHTML='<button id="txt">Add text</button>';$('#txt').onclick=addText}if(n==='shape'){p.innerHTML='<button id="rect">Rectangle</button><button id="circ">Circle</button>';$('#rect').onclick=()=>shape();$('#circ').onclick=()=>shape(true)}if(n==='effect'){p.innerHTML='<button id="gray">Mono</button><button id="reset">Reset</button>';$('#gray').onclick=()=>{let o=canvas.getActiveObject();if(o?.type==='image'){o.filters=[new fabric.Image.filters.Grayscale()];o.applyFilters();canvas.requestRenderAll()}};$('#reset').onclick=()=>{let o=canvas.getActiveObject();if(o?.type==='image'){o.filters=[];o.applyFilters();canvas.requestRenderAll()}}}if(n==='gif'){p.innerHTML='<button id="gif">Choose GIF / image</button>';$('#gif').onclick=()=>{$('#localFile').accept='image/gif,image/*';$('#localFile').click()}}if(n==='layers'){p.innerHTML='<button id="up">Bring forward</button><button id="down">Send back</button>';$('#up').onclick=()=>{let o=canvas.getActiveObject();o&&canvas.bringForward(o)};$('#down').onclick=()=>{let o=canvas.getActiveObject();o&&canvas.sendBackwards(o)}}}
function save(){if(!canvas)return;localStorage.setItem('jittoo-project',JSON.stringify(canvas.toJSON()));toast('Project saved on this device')}
function exportPNG(){if(!canvas)return;let a=document.createElement('a');a.download='jittoo-design.png';a.href=canvas.toDataURL({format:'png',multiplier:2});a.click()}
function bind(){$('#theme').onclick=()=>{theme=theme==='light'?'dark':'light';applyTheme()};$('#premium').onclick=()=>$('#premiumModal').classList.remove('hidden');$('#closePremium').onclick=()=>$('#premiumModal').classList.add('hidden');$('#telegram').onclick=()=>window.open('https://t.me/vcafemm','_blank');$('#activate').onclick=async()=>{let key=$('#premiumKey').value.trim();if(!key)return toast('Enter your premium key');try{let r=await fetch('/api/premium',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})}),d=await r.json();$('#keyResult').textContent=d.valid?'Premium active until '+d.enddate:(d.message||'Invalid key')}catch(e){$('#keyResult').textContent='Premium API is not configured yet.'}};$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#start').onclick=()=>openStudio();$('#openLocal').onclick=()=>$('#localFile').click();$('#localFile').onchange=e=>{let f=e.target.files?.[0];if(f){let r=new FileReader();r.onload=()=>openStudio(r.result);r.readAsDataURL(f)}};$$('.visual-card').forEach(b=>b.onclick=()=>openStudio());renderTemplates();$('#templateGrid').onclick=e=>{if(e.target.closest('.template'))openStudio()};$('#brandForm').onsubmit=e=>{e.preventDefault();localStorage.setItem('jittoo-brand',JSON.stringify({name:$('#brandName').value,tagline:$('#brandTagline').value,contact:$('#brandContact').value}));preview();toast('Business information saved')};['brandName','brandTagline','brandContact'].forEach(id=>$('#'+id).oninput=preview);$('#aiBtn').onclick=()=>{$('#aiResult').textContent=$('#aiPrompt').value?`Creative direction\n\n${$('#aiPrompt').value}\n\nUse a premium editorial composition, clear hierarchy, generous negative space and subtle motion.`:'Describe your creative goal first.'};$('#save').onclick=save;$('#export').onclick=exportPNG;$('#backBtn').onclick=()=>show('home');$$('.tool-dock button').forEach(b=>b.onclick=()=>tool(b.dataset.tool));$('#context').onclick=e=>{let b=e.target.closest('button'),o=canvas?.getActiveObject();if(!b||!o)return;if(b.dataset.tool==='delete')canvas.remove(o);if(b.dataset.tool==='duplicate')o.clone(c=>{c.set({left:o.left+20,top:o.top+20});canvas.add(c)});if(b.dataset.tool==='front')canvas.bringToFront(o);if(b.dataset.tool==='back')canvas.sendToBack(o);canvas.requestRenderAll()}}
function addEvents(){canvas.on('selection:created',()=>$('#context').classList.remove('hidden'));canvas.on('selection:updated',()=>$('#context').classList.remove('hidden'));canvas.on('selection:cleared',()=>$('#context').classList.add('hidden'))}
function preview(){let n=$('#brandName').value||'Your business',t=$('#brandTagline').value||'Your tagline appears here.',c=$('#brandContact').value||'Contact information';$('#previewName').textContent=n;$('#previewTagline').textContent=t;$('#previewContact').textContent=c}
applyTheme();bind();preview();show(['templates','business','ai'].includes(location.hash.slice(1))?location.hash.slice(1):'home');